### ISSUE TITLE
No implementation for QuantizerVisitor::VisitNormalizationLayer()

### ISSUE THREAD

**Issue by soysr** [ARM-software/armnn#216]
**terminate called after throwing an instance of 'armnn::UnimplementedException'
what(): VisitNormalizationLayer
Aborted**

Seems there is no implementation for QuantizerVisitor::VisitNormalizationLayer(); why? It's a fundamental layer...

**Comment by arovir01** [comment]
Yes, we have already been made aware of [this bug](https://github.com/ARM-software/armnn/issues/213)

**Comment by arovir01** [comment]
Fixed in master.

**Comment by soysr** [comment]
@arovir01 thanks! just given a quick try, but the new master branch gives the following compiling errors:
Bug is still unsolved.

**armnn/src/backends/neon/workloads/NeonL2NormalizationFloatWorkload.cpp: In function ‘arm_compute::Status armnn::NeonL2NormalizationWorkloadValidate(const armnn::TensorInfo&, const armnn::TensorInfo&, const armnn::L2NormalizationDescriptor&)’:
armnn/src/backends/neon/workloads/NeonL2NormalizationFloatWorkload.cpp:27:99: error: conversion to ‘unsigned int’ from ‘int’ may change the sign of the result [-Werror=sign-conversion]
     return arm_compute::NEL2NormalizeLayer::validate(&aclInput, &aclOutput, axis, descriptor.m_Eps);
                                                                                                   ^
armnn/src/backends/neon/workloads/NeonL2NormalizationFloatWorkload.cpp: In constructor ‘armnn::NeonL2NormalizationFloatWorkload::NeonL2NormalizationFloatWorkload(const armnn::L2NormalizationQueueDescriptor&, const armnn::WorkloadInfo&, std::shared_ptr<arm_compute::MemoryManagerOnDemand>&)’:
armnn/src/backends/neon/workloads/NeonL2NormalizationFloatWorkload.cpp:46:70: error: conversion to ‘unsigned int’ from ‘int’ may change the sign of the result [-Werror=sign-conversion]
     layer->configure(&input, &output, axis, m_Data.m_Parameters.m_Eps);
                                                                      ^
cc1plus: all warnings being treated as errors
src/backends/neon/workloads/CMakeFiles/armnnNeonBackendWorkloads.dir/build.make:374: recipe for target 'src/backends/neon/workloads/CMakeFiles/armnnNeonBackendWorkloads.dir/NeonL2NormalizationFloatWorkload.cpp.o' failed
make[2]: *** [src/backends/neon/workloads/CMakeFiles/armnnNeonBackendWorkloads.dir/NeonL2NormalizationFloatWorkload.cpp.o] Error 1
CMakeFiles/Makefile2:1342: recipe for target 'src/backends/neon/workloads/CMakeFiles/armnnNeonBackendWorkloads.dir/all' failed
make[1]: *** [src/backends/neon/workloads/CMakeFiles/armnnNeonBackendWorkloads.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2**

**Comment by arovir01** [comment]
I will look into it. In the meantime try building without -Werror=sign-conversion.

**Comment by arovir01** [comment]
What version of Arm Compute Library are you building Arm NN master against? It should be the pinned version from scripts/get_compute_library.sh. Later versions -- such as the head of their master branch -- might contain API breaking changes and are not guaranteed to work with Arm NN (yet).

**Comment by FSet89** [comment]
I cloned the last version of Compute Library from github (`git clone https://github.com/ARM-software/ComputeLibrary`) and I encountered the same problem. I confirm that removing `-Werror=sign-conversion` allows to build armnn.

**Comment by soysr** [comment]
@FSet89 I did exactly the same today
@arovir01 Should I redo using scripts/get_compute_library.sh or not? (compiling takes time)

**Comment by nikraj01** [comment]
Hi @soysr , yes please.

**Comment by Colm-in-Arm** [comment]
Hi @soysr,

Did you get past this issue? If I hear nothing back I'll close this in a week or so.

Colm.
