### ISSUE TITLE
A system's native Boost preferred over the one specifically compiled for ArmNN

### ISSUE THREAD

**Issue by ens-lg4** [ARM-software/armnn#226]
Dear ArmNN developers,

It took me a few days to diagnose a weird family of issues where compilation of ArmNN and consumer programs happened without errors (with some warnings though), and either "Bus Error" or "Segmentation Fault" would appear during the runtime.

This happened on a `hikey960` "host" platform running Debian Linux 9, which also had a pre-installed version of Boost 1.58 or 1.62 (this detail proved to be essential).

According to the documentation ( https://developer.arm.com/solutions/machine-learning-on-arm/developer-material/how-to-guides/configuring-the-arm-nn-sdk-build-environment-for-tensorflow/single-page ) we need Boost 1.64 with -fPIC.  So this is what I compiled and passed on to cmake building the program. When cmake runs, it reports that it found our Boost v.1.64 and PRETENDS to take it into account. However when I switch on all logging I can see that the path to this newly compiled Boost is nowhere to be seen in the command used to link the actual `armnn.so` ! 

The linking command looks like this (I'm skipping the object files in the middle):
```
/usr/bin/cmake -E cmake_link_script CMakeFiles/armnn.dir/link.txt --verbose=1
/usr/bin/clang++-6.0  -fPIC  -std=c++14 -Werror -std=c++14 -Wall -Wold-style-cast -Wno-missing-braces -Wconversion -Wsign-con
version -DNDEBUG -O3  -shared -Wl,-soname,libarmnn.so -o libarmnn.so CMakeFiles/armnn.dir/src/armnn/layers/ActivationLayer.cpp.o CMakeFiles/armnn.dir/src/armnn/layers/AdditionLayer.cpp.o CMakeFiles/armnn.dir/src/armnn/layers/BatchNormalizationLayer.cpp.o CMakeFiles/armnn.dir/src/armnn/layers/BatchToSpaceNdLayer.cpp.o 
...
src/backends/reference/workloads/CMakeFiles/armnnRefBackendWorkloads.dir/RefMeanFloat32Workload.cpp.o src/backends/reference/workloads/CMakeFiles/armnnRefBackendWorkloads.dir/RefMeanUint8Workload.cpp.o libarmnnUtils.a -ldl -Wl,-Bstatic -lboost_log -lboost_thread -lboost_system -Wl,-Bdynamic 
```

Which is immediately followed by reaction from the linker:
```
/usr/bin/ld: /usr/bin/../lib/gcc/aarch64-linux-gnu/7.2.0/../../../aarch64-linux-gnu/libboost_log.a(core.o): relocation R_AARCH64_ADR_PREL_PG_HI21 against symbol `_ZTVN5boost16exception_detail19error_info_injectorISt13runtime_errorEE' which may bind externally can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/bin/../lib/gcc/aarch64-linux-gnu/7.2.0/../../../aarch64-linux-gnu/libboost_log.a(core.o): relocation R_AARCH64_ADR_PREL_PG_HI21 against symbol `_ZTVN5boost9exceptionE' which may bind externally can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/bin/../lib/gcc/aarch64-linux-gnu/7.2.0/../../../aarch64-linux-gnu/libboost_log.a(core.o): relocation R_AARCH64_ADR_PREL_PG_HI21 against symbol `_ZTVN5boost16exception_detail10clone_baseE' which may bind externally can not be used when making a shared object; recompile with -fPIC
...
```

There is either an error or inconsistency in the `cmake/GlobalConfig.cmake` included from the main `CMakeLists.txt` which contains the following bit related to Boost:
```
add_definitions("-DBOOST_ALL_NO_LIB") # Turn off auto-linking as we specify the libs manually
set(Boost_USE_STATIC_LIBS ON)
find_package(Boost 1.59 REQUIRED COMPONENTS unit_test_framework system filesystem log program_options)
include_directories(SYSTEM "${Boost_INCLUDE_DIR}")
link_directories(${Boost_LIBRARY_DIR})
```

It suddenly requires Boost v.1.59 (which does not match 1.64 required by the documentation), however when I patched this to 1.64 my system still insisted on linking with the system's Boost. As you can see from the log above, the `-L` flag necessary to enforce specific Boost's path was missing from the linking command.

However AS SOON AS I uninstalled the system's Boost, everything both compiled and ran without any problems. Please review your `cmake` code related to linking with Boost.

**Comment by MatthewARM** [comment]
Intriguing.

The 1.59 vs. 1.64 thing is intentional - the person who wrote that guide tested with 1.64. "other versions may work." The version of the API we need was introduced in 1.59 so we check that at least that version is available.

However the linking to Boost is clearly not working as intended. Setting BOOST_ROOT on the CMake command line is supposed to make it take boost from that directory no matter what is installed on the system.

I presume you had boost-dev packages installed? Can you let us know exactly what ones were installed so we can try to recreate the problem?

All the best,
Matthew

**Comment by MatthewARM** [comment]
This could fix the problem: https://review.mlplatform.org/c/ml/armnn/+/1540

**Comment by ens-lg4** [comment]
Thanks for your quick reply!

No, this patch (DIR -> DIRS) made no difference unfortunately.

When I remove system's libboost installation everything compiles fine. As soon as I re-install libboost ( `sudo apt-get install libboost-all-dev` on Debian 9 running on `hikey962` ) the problem comes back.

**Comment by MatthewARM** [comment]
Hi @ens-lg4 I'm not seeing this problem, starting with a clean Debian 9 environment, installing libboost-all-dev, then following the build steps.

In order to help diagnose the problem, would you be able to provide some information?

* The version of cmake you are using (`cmake --version`). I am using version 3.7.2.
* The contents of  CMakeFiles/armnn.dir/link.txt in your build directory. I'm specifically worried about the boost link bits, which for me are:
```
../../../install/aarch64/boost/lib/libboost_log.a ../../../install/aarch64/boost/lib/libboost_thread.a ../../../install/aarch64/boost/lib/libboost_system.a
```
It looks to me like you're getting `-lboost_thread` etc. which suggests that CMake is not finding your built static libraries properly.
* The directory listing for your (boost prefix)/lib directory, for me this is:
```
~/gits/devenv$ ls install/aarch64/boost/lib/
libboost_atomic.a     libboost_filesystem.a  libboost_numpy.a             libboost_python.a  libboost_test_exec_monitor.a  libboost_unit_test_framework.a
libboost_chrono.a     libboost_log.a         libboost_prg_exec_monitor.a  libboost_regex.a   libboost_thread.a
libboost_date_time.a  libboost_log_setup.a   libboost_program_options.a   libboost_system.a  libboost_timer.a
```

* The result of `grep -i boost CMakeCache.txt | grep "\(ROOT\)\|\(DIR\)"` in your build directory. For me this is:
```
BOOST_ROOT:PATH=/home/matben01/gits/devenv/install/aarch64/boost
Boost_DIR:PATH=Boost_DIR-NOTFOUND
Boost_INCLUDE_DIR:PATH=/home/matben01/gits/devenv/install/aarch64/boost/include
Boost_LIBRARY_DIR_DEBUG:PATH=/home/matben01/gits/devenv/install/aarch64/boost/lib
Boost_LIBRARY_DIR_RELEASE:PATH=/home/matben01/gits/devenv/install/aarch64/boost/lib
//ADVANCED property for variable: BOOST_ROOT
BOOST_ROOT-ADVANCED:INTERNAL=1
//ADVANCED property for variable: Boost_DIR
Boost_DIR-ADVANCED:INTERNAL=1
//ADVANCED property for variable: Boost_INCLUDE_DIR
Boost_INCLUDE_DIR-ADVANCED:INTERNAL=1
//ADVANCED property for variable: Boost_LIBRARY_DIR_DEBUG
Boost_LIBRARY_DIR_DEBUG-ADVANCED:INTERNAL=1
//ADVANCED property for variable: Boost_LIBRARY_DIR_RELEASE
Boost_LIBRARY_DIR_RELEASE-ADVANCED:INTERNAL=1
//Last used BOOST_ROOT value.
_BOOST_ROOT_LAST:INTERNAL=/home/matben01/gits/devenv/install/aarch64/boost
//Last used Boost_INCLUDE_DIR value.
_Boost_INCLUDE_DIR_LAST:INTERNAL=/home/matben01/gits/devenv/install/aarch64/boost/include
//Last used Boost_LIBRARY_DIR_DEBUG value.
_Boost_LIBRARY_DIR_DEBUG_LAST:INTERNAL=/home/matben01/gits/devenv/install/aarch64/boost/lib
//Last used Boost_LIBRARY_DIR_RELEASE value.
_Boost_LIBRARY_DIR_RELEASE_LAST:INTERNAL=/home/matben01/gits/devenv/install/aarch64/boost/lib
```

I am basically wondering if something is cached somewhere in your build that is making things go wrong, or if there is some different behaviour of something on your system that is a different version to mine.

All the best,
Matthew

**Comment by ens-lg4** [comment]
Exacty the same thing happens on an Intel machine running Ubuntu 16.04 and newer version of cmake (3.14.3 vs 3.7.2 on hikey960) and even older and incompatible version of Boost 1.58.

The main problem seems to be that the full paths to the libraries that FindBoost.cmake manages to find (with or without hints - doesn't matter) never make their way to the linking command - the `-L` option is never used, so when `ld` grabs controls, it prefers system's Boost to anything else.

On `hikey960` I am running `Debian 9` with `cmake 3.7.2` (same as you).

Here are my boost libraries bespoke-compiled for ArmNN (both static and shared in my case):
```
libboost_atomic.a              libboost_log_setup.so                libboost_system.so
libboost_atomic.so             libboost_log_setup.so.1.64.0         libboost_system.so.1.64.0
libboost_atomic.so.1.64.0      libboost_log.so                      libboost_test_exec_monitor.a
libboost_chrono.a              libboost_log.so.1.64.0               libboost_thread.a
libboost_chrono.so             libboost_prg_exec_monitor.a          libboost_thread.so
libboost_chrono.so.1.64.0      libboost_prg_exec_monitor.so         libboost_thread.so.1.64.0
libboost_date_time.a           libboost_prg_exec_monitor.so.1.64.0  libboost_timer.a
libboost_date_time.so          libboost_program_options.a           libboost_timer.so
libboost_date_time.so.1.64.0   libboost_program_options.so          libboost_timer.so.1.64.0
libboost_filesystem.a          libboost_program_options.so.1.64.0   libboost_unit_test_framework.a
libboost_filesystem.so         libboost_regex.a                     libboost_unit_test_framework.so
libboost_filesystem.so.1.64.0  libboost_regex.so                    libboost_unit_test_framework.so.1.64.0
libboost_log.a                 libboost_regex.so.1.64.0
libboost_log_setup.a           libboost_system.a
```

This is how the ArmNN linking command from `CMakeFiles/armnn.dir/link.txt` ends for me:
```
libarmnnUtils.a -ldl -Wl,-Bstatic -lboost_log -lboost_thread -lboost_system -Wl,-Bdynamic
```

The result of `grep -i boost CMakeCache.txt | grep "\(ROOT\)\|\(DIR\)"` for me is:
```
BOOST_ROOT:PATH=/home/lg4/CK-TOOLS/lib-boost-1.64.0-llvm-6.0.0-1~bpo9+1-for-armnn-shared-linux-64/install
Boost_INCLUDE_DIR:PATH=/home/lg4/CK-TOOLS/lib-boost-1.64.0-llvm-6.0.0-1~bpo9+1-for-armnn-shared-linux-64/install/include
Boost_LIBRARY_DIR_DEBUG:PATH=/home/lg4/CK-TOOLS/lib-boost-1.64.0-llvm-6.0.0-1~bpo9+1-for-armnn-shared-linux-64/install/lib
Boost_LIBRARY_DIR_RELEASE:PATH=/home/lg4/CK-TOOLS/lib-boost-1.64.0-llvm-6.0.0-1~bpo9+1-for-armnn-shared-linux-64/install/lib
//ADVANCED property for variable: BOOST_ROOT
BOOST_ROOT-ADVANCED:INTERNAL=1
//ADVANCED property for variable: Boost_INCLUDE_DIR
Boost_INCLUDE_DIR-ADVANCED:INTERNAL=1
//ADVANCED property for variable: Boost_LIBRARY_DIR_DEBUG
Boost_LIBRARY_DIR_DEBUG-ADVANCED:INTERNAL=1
//ADVANCED property for variable: Boost_LIBRARY_DIR_RELEASE
Boost_LIBRARY_DIR_RELEASE-ADVANCED:INTERNAL=1
//Last used BOOST_ROOT value.
_BOOST_ROOT_LAST:INTERNAL=/home/lg4/CK-TOOLS/lib-boost-1.64.0-llvm-6.0.0-1~bpo9+1-for-armnn-shared-linux-64/install
//Last used Boost_INCLUDE_DIR value.
_Boost_INCLUDE_DIR_LAST:INTERNAL=/home/lg4/CK-TOOLS/lib-boost-1.64.0-llvm-6.0.0-1~bpo9+1-for-armnn-shared-linux-64/install/include
//Last used Boost_LIBRARY_DIR_DEBUG value.
_Boost_LIBRARY_DIR_DEBUG_LAST:INTERNAL=/home/lg4/CK-TOOLS/lib-boost-1.64.0-llvm-6.0.0-1~bpo9+1-for-armnn-shared-linux-64/install/lib
//Last used Boost_LIBRARY_DIR_RELEASE value.
_Boost_LIBRARY_DIR_RELEASE_LAST:INTERNAL=/home/lg4/CK-TOOLS/lib-boost-1.64.0-llvm-6.0.0-1~bpo9+1-for-armnn-shared-linux-64/install/lib
```

**Comment by MatthewARM** [comment]
The thing is it shouldn't pass "-L" to the linker because it should be using relative paths to the libraries.

And you're not getting "Boost_DIR" references in your CMakeCache.txt. It's as if the version of FindBoost.cmake is different.

Just out of interest, are you using the master branch? Or a release tag?

**Comment by ens-lg4** [comment]
I have tested both `rel.19.02` tag and `rel.19.05` tag.

My cmake definitely finds the right Boost, because during the execution it always prints:
```
-- Boost version: 1.64.0
-- Found the following Boost libraries:
--   unit_test_framework
--   system
--   filesystem
--   log
--   program_options
--   date_time
--   log_setup
--   thread
--   regex
--   chrono
--   atomic
```

The version of system's `FindBoost.cmake` should not make any difference, because ArmNN brings its' own, and includes it explicitly.

Having noticed that you only compiled Boost in static mode (no `.so` files in the directory) I thought maybe cmake gets confused with both versions? So I recompiled Boost, but the end result is unfortunately the same.

**Comment by ens-lg4** [comment]
I think my log does not show `Boost_DIR`, because I was running `cmake` with `-DBoost_NO_BOOST_CMAKE=TRUE`  (I tried both ways now - no difference).

**Comment by ens-lg4** [comment]
BTW, documentation for [link_directories](https://cmake.org/cmake/help/v3.7/command/link_directories.html) says:

> Note that this command is rarely necessary. Library locations returned by find_package() and find_library() are absolute paths. Pass these absolute library file paths directly to the target_link_libraries() command. CMake will ensure the linker finds them.

**Comment by ens-lg4** [comment]
Eureka!!!

If `cmake` detects that boost's libraries are found in `$LIBRARY_PATH` and/or `$LD_LIBRARY_PATH`, then instead of paths to the libraries it substitutes the `-Wl,-Bstatic -lboost_log -lboost_thread -lboost_system -Wl,-Bdynamic` bit.  I don't know yet if this functionality can be blocked, but when I clean up both `$LIBRARY_PATH` and `$LD_LIBRARY_PATH` variables just before running `cmake`, my linking command looks just like yours. And the linker suddenly behaves!

* * *

To reproduce you may need to set your `$LIBRARY_PATH` and `$LD_LIBRARY_PATH` variables to the path to the correct (!) Boost , then export them and run `cmake`.

**Comment by ens-lg4** [comment]
The problem seems to be rather old: https://cmake.org/pipermail/cmake/2011-June/044782.html

**Comment by MatthewARM** [comment]
Thanks @ens-lg4 that explains it all.

From the mailing list, I guess the proper way to fix this would be to create "imported targets" for the boost libraries, and link to them. I seem to remember reading somewhere that this is generally good practice for dependencies in CMake in any case.

As there is a workaround (clear LIBRARY_PATH) how high priority do you think this should be?

**Comment by ens-lg4** [comment]
I'm not sure. I can clear `$LIBRARY_PATH` before running `cmake` on my side, but other people may still run into the same problem independently. (It is quite counter-intuitive that adding the correct library path to `$LIBRARY_PATH` could potentially break things rather than fix them.).

I'm happy this issue got at least documented here, but also wonder if enforcing `set(ENV{LIBRARY_PATH} "")` near the beginning of `CMakeLists.txt` would solve it better, once and for all?

**Comment by MatthewARM** [comment]
Mm good question. The question in that case is "is there a (currently working) legitimate reason to use LIBRARY_PATH + cmake" that we would break? (e.g, creating a system with multiple installed library roots? http://modules.sourceforge.net/?)

Unless we pretty sure that the answer is "no", I think I'd rather fix it properly instead of applying a workaround that could break something else.

**Comment by FrancisMurtagh-arm** [comment]
Closing as I believe it is fixed with patch:
If56874aaafe1577888f73719f0a493088d1ac531

**Comment by MatthewARM** [comment]
To clarify - review If56874aaafe1577888f73719f0a493088d1ac531 was merged as commit https://github.com/ARM-software/armnn/commit/97fb2debf792ec5ccd0c6bbc5d12df7133b9e01f but it did not fix the issue. 
The problem is with CMake itself, see https://cmake.org/pipermail/cmake/2011-June/044782.html and the workaround is to unset LIBRARY_PATH before running cmake.
This will not be a problem long-term as we remove dependency on boost.
